global:
  scrape_interval: 5s  # ambil data setiap 5 detik

scrape_configs:
  - job_name: 'loan_prediction_api'
    static_configs:
      # ganti ke localhost:5001 sesaui server python
      - targets: ['localhost:5001']